import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Script
        src="https://applepay.cdn-apple.com/jsapi/v1/apple-pay-sdk.js"
        strategy="afterInteractive"
      /> */}
      <Script
        src="https://js.braintreegateway.com/web/3.103.0/js/client.min.js"
        strategy="afterInteractive"
      />
      <Script
        src="https://js.braintreegateway.com/web/3.103.0/js/apple-pay.min.js"
        strategy="afterInteractive"
      />

      {/* <script src="https://js.braintreegateway.com/web/3.103.0/js/client.min.js"></script> 
      <script src="https://js.braintreegateway.com/web/3.103.0/js/apple-pay.min.js"></script> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
